[package]
name = "rustmemtest"
version = "0.1.0"
authors = ["Donovan Harscoet <donovan.harscoet@gmail.com>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = ["macros"] }
warp = "0.2"